const app=document.getElementById('app');let token=localStorage.getItem('elk_token'),page='dashboard',me=null;
const nav=[['dashboard','Dashboard','▦'],['customers','Customers','◉'],['collections','Collections','♻'],['payments','Payments','₵'],['trips','Transport','↗'],['deliveries','Landfill','▣'],['assignments','Assignments','⚑'],['staff','Staff','●'],['trucks','Fleet','▤'],['reports','Reports','▥'],['sms','SMS','✉'],['email','Email','@'],['whatsapp','WhatsApp','◉'],['audit','Audit','✓']];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>'GHS '+Number(n||0).toLocaleString('en-GH',{minimumFractionDigits:2,maximumFractionDigits:2});
const dt=x=>x?new Date(x).toLocaleString('en-GH',{dateStyle:'medium',timeStyle:'short'}):'—';
async function api(path,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};if(opt.body&&typeof opt.body!=='string'){opt.headers['Content-Type']='application/json';opt.body=JSON.stringify(opt.body)}let r=await fetch(path,opt);if(r.status===401){localStorage.removeItem('elk_token');token=null;me=null;render();throw Error('Session expired. Please sign in again.')}let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Request failed');return d}
function login(){app.innerHTML=`<div class="login"><div class="loginbox"><img class="loginlogo" src="/static/branding/el-kalel-logo.png" alt="EL-KALEL ENTERPRISE logo"><div class="mark">EL-KALEL ENTERPRISE</div><h1>Operations Control</h1><p>Waste Management Operations System</p><input id="u" placeholder="Username" value="admin"><input id="p" type="password" placeholder="Password"><button class="btn" onclick="doLogin()">Sign in</button><div class="loginhint">Change the development password before production.</div><div id="err"></div></div></div>`}
async function doLogin(){try{let d=await api('/api/login',{method:'POST',body:{username:u.value,password:p.value}});token=d.token;me=d.user;localStorage.setItem('elk_token',token);render()}catch(e){err.innerHTML='<p class="error">'+esc(e.message)+'</p>'}}
const allowed=p=>{if(!me)return false;if(me.role==='super_admin')return true;const map={customers:['manage_customers','admin','manager'],collections:['operations','collector','driver','admin','manager','dispatcher'],payments:['finance','admin'],trips:['operations','driver','collector','admin','manager','dispatcher'],deliveries:['operations','admin','manager','dispatcher'],assignments:['manage_assignments','admin','manager','dispatcher'],staff:['manage_staff','admin','manager'],trucks:['manage_trucks','admin','manager'],reports:['reports','admin','manager','finance','dispatcher','viewer'],sms:['sms','admin','manager','finance'],email:['email','admin','manager','finance'],whatsapp:['sms','admin','manager','finance'],audit:['reports','admin','manager']};return (map[p]||[]).some(x=>x===me.role||x===rolePermission(me.role))};
function rolePermission(role){return {admin:'admin',manager:'manager',finance:'finance',dispatcher:'dispatcher',collector:'operations',driver:'operations',viewer:'reports'}[role]||role}
function shell(content){const visible=nav.filter(x=>allowed(x[0]));app.innerHTML=`<div class="shell"><aside class="side"><div class="brand"><img class="brandlogo" src="/static/branding/el-kalel-logo.png" alt="EL-KALEL ENTERPRISE"><div><b>EL-KALEL</b><small>ENTERPRISE</small></div></div><div class="nav">${visible.map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')"><span>${x[2]}</span>${x[1]}</button>`).join('')}</div><div class="sidefoot">Waste • Fleet • Finance<br><span>Operations Control v5</span></div></aside><main class="main"><header class="top"><div><div class="eyebrow">EL-KALEL ENTERPRISE</div><h1>${nav.find(x=>x[0]===page)?.[1]||'Dashboard'}</h1></div><div class="user"><span>${esc(me?.username||'User')} · ${esc(me?.role||'')}</span><button class="btn secondary" onclick="logout()">Sign out</button></div></header>${content}</main><nav class="mobile-nav">${visible.slice(0,7).map(x=>`<button class="${page===x[0]?'active':''}" onclick="go('${x[0]}')"><b>${x[2]}</b><small>${x[1]}</small></button>`).join('')}</nav></div>`}
function go(p){if(!allowed(p))return alert('You do not have permission for this section.');page=p;render()}function logout(){localStorage.removeItem('elk_token');token=null;me=null;render()}
async function render(){if(!token)return login();try{if(!me)me=await api('/api/me');return ({dashboard:dash,customers,collections,payments,trips,deliveries,assignments,staff,trucks,reports,sms,email,whatsapp,audit}[page]||dash)()}catch(e){shell(`<div class="notice">${esc(e.message)}</div>`)} }
function cards(items){return `<div class="grid metrics">${items.map(x=>`<div class="card metric"><span class="label">${x[0]}</span><strong>${x[1]}</strong><span class="hint">${x[2]||''}</span></div>`).join('')}</div>`}
async function dash(){let d=await api('/api/dashboard');shell(cards([['Collections today',d.today.collections,'Door-to-door'],['Payments today',money(d.today.payments),'Received'],['Missed today',d.today.missed,'Needs follow-up'],['Outstanding',money(d.outstanding_balance),'Active accounts'],['Trips today',d.today.trips,'Transport'],['Trips in progress',d.in_transit,'On route'],['Active customers',d.active_customers,'Registered'],['Active trucks',d.active_trucks,'Available / on route']])+`<div class="section grid2"><div class="card"><div class="cardhead"><h2>Last 7 days</h2><span class="badge good">LIVE</span></div><div class="miniStats"><div><b>${d.last_7_days.collections}</b><small>Collections</small></div><div><b>${money(d.last_7_days.payments)}</b><small>Payments</small></div><div><b>${d.last_7_days.landfill_tons.toFixed(2)} t</b><small>Landfill</small></div></div></div><div class="card"><div class="cardhead"><h2>Collection by area</h2><button class="btn secondary" onclick="go('collections')">Open</button></div>${table(['Area','Collections'],d.collections_by_area.map(r=>`<tr><td>${esc(r.area)}</td><td><b>${r.count}</b></td></tr>`).join(''))}</div></div><div class="section grid2"><div class="card"><h2>Quick actions</h2><div class="toolbar" style="margin-top:14px"><button class="btn" onclick="go('collections')">Record collection</button><button class="btn secondary" onclick="go('payments')">Record payment</button><button class="btn secondary" onclick="go('trips')">Start trip</button></div></div><div class="card"><h2>Accountability</h2><p>Every important action is timestamped and linked to the signed-in user. Collection records can include GPS coordinates and proof photos.</p><button class="btn secondary" onclick="go('audit')">Open audit trail</button></div></div>`)}
function table(headers,rows){return `<div class="tablewrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}" class="empty">No records found.</td></tr>`}</tbody></table></div>`}
async function customers(){let rows=await api('/api/customers');shell(`<div class="card"><div class="toolbar"><input id="q" placeholder="Search name, phone or code" oninput="filterCustomers()"><input id="area" placeholder="Filter area" oninput="filterCustomers()"><button class="btn" onclick="customerForm()">+ New customer</button><button class="btn secondary" onclick="exportData('customers')">Export CSV</button></div><div id="customerTable">${customerRows(rows)}</div></div>`)}
function customerRows(rows){return table(['Code','Customer','Phone','Area','Monthly fee','Balance','Status','Action'],rows.map(r=>`<tr><td><b>${esc(r.customer_code)}</b></td><td>${esc(r.name)}</td><td>${esc(r.phone)}</td><td>${esc(r.area)}</td><td>${money(r.monthly_fee)}</td><td class="${r.balance>0?'debt':''}">${money(r.balance)}</td><td><span class="badge">${esc(r.status)}</span></td><td><div class="actions"><button class="mini" onclick="statement(${r.id})">Statement</button><button class="mini" onclick="editCustomer(${r.id})">Edit</button>${r.status==='active'?`<button class="mini" onclick="deactivateCustomer(${r.id})">Deactivate</button>`:`<button class="mini" onclick="activateCustomer(${r.id})">Activate</button>`}<button class="mini danger" onclick="deleteCustomer(${r.id})">Delete</button></div></td></tr>`).join(''))}
async function filterCustomers(){let rows=await api('/api/customers?q='+encodeURIComponent(q.value)+'&area='+encodeURIComponent(area.value));document.getElementById('customerTable').innerHTML=customerRows(rows)}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div id="modal" class="modal"><div class="modalbox"><div class="cardhead"><h2>${title}</h2><button class="x" onclick="modal.remove()">×</button></div>${body}</div></div>`)}
function customerForm(){modal('Register customer',`<div class="formgrid"><input id="cn" placeholder="Full name"><input id="cp" placeholder="Phone"><input id="ca" placeholder="Address"><input id="carea" placeholder="Area"><input id="fee" type="number" step="0.01" placeholder="Monthly fee"><input id="due" type="number" min="1" max="31" value="1" placeholder="Payment due day"><input id="cem" type="email" placeholder="Email address (optional)"><input id="cwa" placeholder="WhatsApp number (optional)"><label class="check"><input id="copt" type="checkbox"> Customer opted in to WhatsApp notifications</label></div><div class="actions"><button class="btn" onclick="saveCustomer()">Save customer</button></div>`)}
async function saveCustomer(){try{await api('/api/customers',{method:'POST',body:{name:cn.value.trim(),phone:cp.value.trim(),address:ca.value.trim(),area:carea.value.trim(),monthly_fee:+fee.value||0,payment_due_day:+due.value||1,email:cem.value.trim(),whatsapp_number:cwa.value.trim(),whatsapp_opt_in:copt.checked}});modal.remove();customers()}catch(e){alert(e.message)}}
async function editCustomer(id){let d=await api('/api/customers/'+id+'/statement');let c=d.customer;modal('Edit customer',`<div class="formgrid"><input id="en" value="${esc(c.name)}" placeholder="Full name"><input id="ep" value="${esc(c.phone)}" placeholder="Phone"><input id="ea" value="${esc(c.address)}" placeholder="Address"><input id="earea" value="${esc(c.area)}" placeholder="Area"><input id="efee" type="number" step="0.01" value="${c.monthly_fee}" placeholder="Monthly fee"><input id="edue" type="number" min="1" max="31" value="${c.payment_due_day}" placeholder="Payment due day"><input id="eem" type="email" value="${esc(c.email||'')}" placeholder="Email address"><input id="ewa" value="${esc(c.whatsapp_number||'')}" placeholder="WhatsApp number"><select id="estatus"><option value="active" ${c.status==='active'?'selected':''}>Active</option><option value="inactive" ${c.status!=='active'?'selected':''}>Inactive</option></select><label class="check"><input id="eopt" type="checkbox" ${c.whatsapp_opt_in?'checked':''}> WhatsApp notifications opted in</label></div><div class="actions"><button class="btn" onclick="saveCustomerEdit(${id})">Save changes</button></div>`)}
async function saveCustomerEdit(id){try{await api('/api/customers/'+id,{method:'PUT',body:{name:en.value.trim(),phone:ep.value.trim(),address:ea.value.trim(),area:earea.value.trim(),monthly_fee:+efee.value||0,payment_due_day:+edue.value||1,email:eem.value.trim(),whatsapp_number:ewa.value.trim(),whatsapp_opt_in:eopt.checked,status:estatus.value}});modal.remove();customers()}catch(e){alert(e.message)}}
async function deactivateCustomer(id){if(!confirm('Deactivate this customer? They will remain in the records but will no longer count as active.'))return;try{let d=await api('/api/customers/'+id+'/statement');let c=d.customer;await api('/api/customers/'+id,{method:'PUT',body:{name:c.name,phone:c.phone,address:c.address,area:c.area,monthly_fee:c.monthly_fee,payment_due_day:c.payment_due_day,email:c.email||'',whatsapp_number:c.whatsapp_number||'',whatsapp_opt_in:!!c.whatsapp_opt_in,status:'inactive'}});customers()}catch(e){alert(e.message)}}
async function activateCustomer(id){try{let d=await api('/api/customers/'+id+'/statement');let c=d.customer;await api('/api/customers/'+id,{method:'PUT',body:{name:c.name,phone:c.phone,address:c.address,area:c.area,monthly_fee:c.monthly_fee,payment_due_day:c.payment_due_day,email:c.email||'',whatsapp_number:c.whatsapp_number||'',whatsapp_opt_in:!!c.whatsapp_opt_in,status:'active'}});customers()}catch(e){alert(e.message)}}
async function deleteCustomer(id){if(!confirm('Delete this customer permanently? Only customers with no payment or collection records can be deleted.'))return;try{await api('/api/customers/'+id,{method:'DELETE'});customers()}catch(e){alert(e.message)}}
async function statement(id){let d=await api('/api/customers/'+id+'/statement');modal('Customer statement',`<div class="notice"><b>${esc(d.customer.customer_code)} — ${esc(d.customer.name)}</b><br>Balance: <b>${money(d.customer.balance)}</b></div><h3>Payments</h3>${table(['Amount','Method','Reference','Date'],d.payments.map(p=>`<tr><td>${money(p.amount)}</td><td>${esc(p.method)}</td><td>${esc(p.reference||'—')}</td><td>${dt(p.received_at)}</td></tr>`).join(''))}<h3>Recent collections</h3>${table(['Area','Status','Quantity','Date'],d.collections.map(c=>`<tr><td>${esc(c.area)}</td><td>${esc(c.status)}</td><td>${c.quantity}</td><td>${dt(c.collected_at)}</td></tr>`).join(''))}`)}
async function collections(){let rows=await api('/api/collections');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="collectionForm()">+ Record collection</button><button class="btn secondary" onclick="syncOffline()">Sync offline queue</button><button class="btn secondary" onclick="exportData('collections')">Export CSV</button><input id="cq" placeholder="Filter area" oninput="filterCollections()"><select id="csf" onchange="filterCollections()"><option value="">All statuses</option><option>collected</option><option>partial</option><option>missed</option></select></div><div id="collectionTable">${collectionRows(rows)}</div></div>`)}
function collectionRows(rows){return table(['Customer','Area','Status','Qty','GPS','Offline','Time'],rows.map(r=>`<tr><td>#${r.customer_id}</td><td>${esc(r.area)}</td><td><span class="badge">${esc(r.status)}</span></td><td>${r.quantity}</td><td>${r.latitude?`${Number(r.latitude).toFixed(4)}, ${Number(r.longitude).toFixed(4)}`:'—'}</td><td>${r.offline_recorded?'Yes':'No'}</td><td>${dt(r.collected_at)}</td></tr>`).join(''))}
async function filterCollections(){let rows=await api('/api/collections?area='+encodeURIComponent(cq.value)+'&status='+encodeURIComponent(csf.value));document.getElementById('collectionTable').innerHTML=collectionRows(rows)}
async function collectionForm(){let [cs,st,tr]=await Promise.all([api('/api/customers'),api('/api/staff'),api('/api/trucks')]);modal('Record door-to-door collection',`<div class="form"><select id="cc">${cs.map(c=>`<option value="${c.id}">${esc(c.customer_code)} — ${esc(c.name)} — ${esc(c.area)}</option>`).join('')}</select><input id="carea2" placeholder="Area"><div class="formgrid"><select id="cstaff"><option value="">Collector</option>${st.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><select id="ctruck"><option value="">Truck</option>${tr.map(t=>`<option value="${t.id}">${esc(t.plate_number)}</option>`).join('')}</select></div><div class="formgrid"><input id="qty" type="number" step="0.1" placeholder="Quantity / bags"><select id="cstatus"><option>collected</option><option>partial</option><option>missed</option></select></div><input id="cnote" placeholder="Notes"><p class="muted">GPS will be captured from the phone when available.</p></div><div class="actions"><button class="btn" onclick="saveCollection()">Save collection</button></div>`)}
function getGPS(){return new Promise(resolve=>{if(!navigator.geolocation)return resolve({});navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude}),()=>resolve({}),{enableHighAccuracy:true,timeout:7000})})}
async function saveCollection(){const gps=await getGPS();const body={customer_id:+cc.value,area:carea2.value,staff_id:cstaff.value?+cstaff.value:null,truck_id:ctruck.value?+ctruck.value:null,status:cstatus.value,quantity:+qty.value||0,notes:cnote.value,...gps,device_id:navigator.userAgent.slice(0,100)};try{await api('/api/collections',{method:'POST',body});alert('Collection recorded.')}catch(e){const q=JSON.parse(localStorage.getItem('elk_offline_collections')||'[]');q.push(body);localStorage.setItem('elk_offline_collections',JSON.stringify(q));alert('No connection. Saved to the phone and will sync later.')}modal.remove();collections()}
async function syncOffline(){const q=JSON.parse(localStorage.getItem('elk_offline_collections')||'[]');if(!q.length)return alert('No offline records to sync.');try{let r=await api('/api/collections/sync',{method:'POST',body:{records:q.map(x=>({...x,offline_recorded:true}))}});localStorage.removeItem('elk_offline_collections');alert(`${r.saved} offline records synced.`);collections()}catch(e){alert('Sync failed: '+e.message)}}
async function payments(){let rows=await api('/api/payments');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="paymentForm()">+ Record payment</button><button class="btn secondary" onclick="exportData('payments')">Export CSV</button></div>${table(['Customer','Amount','Method','Reference','Receipt','Date'],rows.map(r=>`<tr><td>#${r.customer_id}</td><td><b>${money(r.amount)}</b></td><td>${esc(r.method)}</td><td>${esc(r.reference||'—')}</td><td>${esc(r.receipt_no||'—')}</td><td>${dt(r.received_at)}</td></tr>`).join(''))}</div>`)}
async function paymentForm(){let cs=await api('/api/customers');modal('Record customer payment',`<div class="form"><select id="pc">${cs.map(c=>`<option value="${c.id}">${esc(c.customer_code)} — ${esc(c.name)} — balance ${money(c.balance)}</option>`).join('')}</select><input id="pa" type="number" step="0.01" placeholder="Amount"><select id="pm"><option>MTN MoMo</option><option>Cash</option><option>Bank</option><option>Other</option></select><input id="pr" placeholder="Reference / transaction ID"><input id="prec" placeholder="Receipt number"><input id="pn" placeholder="Notes"></div><div class="actions"><button class="btn" onclick="savePayment()">Save payment</button></div>`)}
async function savePayment(){let d=await api('/api/payments',{method:'POST',body:{customer_id:+pc.value,amount:+pa.value,method:pm.value,reference:pr.value,receipt_no:prec.value,notes:pn.value}});modal.remove();alert('Payment saved. New balance: '+money(d.customer_balance));payments()}
async function trips(){let rows=await api('/api/trips');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="tripForm()">+ Start trip</button><button class="btn secondary" onclick="exportData('trips')">Export CSV</button></div>${table(['Truck','Area','Destination','Status','Departed','Returned','Action'],rows.map(r=>`<tr><td>#${r.truck_id}</td><td>${esc(r.area)}</td><td>${esc(r.destination)}</td><td><span class="badge">${esc(r.status)}</span></td><td>${dt(r.departed_at)}</td><td>${dt(r.returned_at)}</td><td>${r.status==='in_progress'?`<button class="mini" onclick="returnTrip(${r.id})">Close trip</button>`:'—'}</td></tr>`).join(''))}</div>`)}
async function returnTrip(id){let end=prompt('End odometer km (optional):','');await api('/api/trips/'+id+'/return',{method:'POST',body:{odometer_end:end?+end:null}});trips()}
async function tripForm(){let [tr,st]=await Promise.all([api('/api/trucks'),api('/api/staff')]);modal('Start transport trip',`<div class="form"><select id="tt">${tr.map(t=>`<option value="${t.id}">${esc(t.plate_number)} — ${esc(t.name)} (${esc(t.status)})</option>`).join('')}</select><select id="tdriver"><option value="">Driver</option>${st.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><input id="ta" placeholder="Area"><input id="td" placeholder="Destination" value="Landfill"><input id="tk" type="number" step="0.1" placeholder="Distance km"><input id="tos" type="number" step="0.1" placeholder="Start odometer km"><input id="tno" placeholder="Notes"></div><div class="actions"><button class="btn" onclick="saveTrip()">Start trip</button></div>`)}
async function saveTrip(){let gps=await getGPS();await api('/api/trips',{method:'POST',body:{truck_id:+tt.value,driver_id:tdriver.value?+tdriver.value:null,area:ta.value,destination:td.value,distance_km:+tk.value||0,odometer_start:+tos.value||0,...gps,notes:tno.value}});modal.remove();trips()}
async function deliveries(){let rows=await api('/api/landfill-deliveries');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="deliveryForm()">+ Record landfill delivery</button><button class="btn secondary" onclick="exportData('deliveries')">Export CSV</button></div>${table(['Trip','Weight','Receipt','Date','Notes'],rows.map(r=>`<tr><td>#${r.trip_id}</td><td>${r.weight_tons} tons</td><td>${esc(r.receipt_no||'—')}</td><td>${dt(r.delivered_at)}</td><td>${esc(r.notes||'')}</td></tr>`).join(''))}</div>`)}
async function deliveryForm(){let tr=await api('/api/trips');modal('Record landfill delivery',`<div class="form"><select id="dltrip">${tr.map(t=>`<option value="${t.id}">Trip #${t.id} — ${esc(t.area)} — ${esc(t.destination)}</option>`).join('')}</select><input id="dlweight" type="number" step="0.01" placeholder="Weight (tons)"><input id="dlreceipt" placeholder="Landfill receipt number"><input id="dlnote" placeholder="Notes"></div><div class="actions"><button class="btn" onclick="saveDelivery()">Save delivery</button></div>`)}
async function saveDelivery(){await api('/api/landfill-deliveries',{method:'POST',body:{trip_id:+dltrip.value,weight_tons:+dlweight.value,receipt_no:dlreceipt.value,notes:dlnote.value}});modal.remove();deliveries()}
async function assignments(){let rows=await api('/api/assignments');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="assignmentForm()">+ New assignment</button></div>${table(['Area','Staff','Truck','Date','Status','Notes'],rows.map(r=>`<tr><td>${esc(r.area)}</td><td>#${r.staff_id}</td><td>#${r.truck_id||'—'}</td><td>${dt(r.assignment_date)}</td><td>${esc(r.status)}</td><td>${esc(r.notes||'')}</td></tr>`).join(''))}</div>`)}
async function assignmentForm(){let [st,tr]=await Promise.all([api('/api/staff'),api('/api/trucks')]);modal('Assign team and truck',`<div class="form"><input id="aa" placeholder="Service area"><select id="astaff">${st.map(s=>`<option value="${s.id}">${esc(s.name)} — ${esc(s.role)}</option>`).join('')}</select><select id="atruck"><option value="">No truck</option>${tr.map(t=>`<option value="${t.id}">${esc(t.plate_number)}</option>`).join('')}</select><input id="anote" placeholder="Notes"></div><div class="actions"><button class="btn" onclick="saveAssignment()">Save assignment</button></div>`)}
async function saveAssignment(){await api('/api/assignments',{method:'POST',body:{area:aa.value,staff_id:+astaff.value,truck_id:atruck.value?+atruck.value:null,notes:anote.value}});modal.remove();assignments()}
async function staff(){let rows=await api('/api/staff');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="staffForm()">+ Add staff</button></div>${table(['Name','Phone','Role','Status'],rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.phone)}</td><td>${esc(r.role)}</td><td>${r.active?'Active':'Inactive'}</td></tr>`).join(''))}</div>`)}
function staffForm(){modal('Add staff member',`<div class="form"><input id="sn" placeholder="Name"><input id="sp" placeholder="Phone"><input id="sr" placeholder="Role"></div><div class="actions"><button class="btn" onclick="saveStaff()">Save</button></div>`)}
async function saveStaff(){await api('/api/staff',{method:'POST',body:{name:sn.value,phone:sp.value,role:sr.value,active:true}});modal.remove();staff()}
async function trucks(){let rows=await api('/api/trucks');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="truckForm()">+ Add truck</button></div>${table(['Plate','Name','Capacity','Status','Odometer','Fuel','Service due'],rows.map(r=>`<tr><td><b>${esc(r.plate_number)}</b></td><td>${esc(r.name)}</td><td>${r.capacity}</td><td><span class="badge">${esc(r.status)}</span></td><td>${r.odometer_km} km</td><td>${r.fuel_liters} L</td><td>${r.next_service_due_km||'—'} km</td></tr>`).join(''))}</div>`)}
function truckForm(){modal('Register truck',`<div class="formgrid"><input id="tp" placeholder="Plate number"><input id="tn" placeholder="Truck name"><input id="tc" type="number" placeholder="Capacity"><input id="to" type="number" placeholder="Current odometer km"><input id="tf" type="number" placeholder="Fuel litres"><input id="ts" type="number" placeholder="Next service at km"></div><div class="actions"><button class="btn" onclick="saveTruck()">Save</button></div>`)}
async function saveTruck(){await api('/api/trucks',{method:'POST',body:{plate_number:tp.value,name:tn.value,capacity:+tc.value||0,status:'available',odometer_km:+to.value||0,fuel_liters:+tf.value||0,next_service_due_km:+ts.value||0}});modal.remove();trucks()}
async function reports(){let d=await api('/api/reports/summary?days=30');shell(`<div class="card"><div class="cardhead"><h2>30-day performance</h2><div class="toolbar"><button class="btn secondary" onclick="reports()">Refresh</button><button class="btn secondary" onclick="exportData('customers')">Customers CSV</button><button class="btn secondary" onclick="exportData('payments')">Payments CSV</button></div></div>${cards([['Collections',d.collections,'Last 30 days'],['Missed',d.missed_collections,'Follow-up required'],['Payments',money(d.payments),'Received'],['Landfill',d.landfill_tons.toFixed(2)+' tons','Delivered'],['Trips',d.trips,'Started'],['New customers',d.new_customers,'Registered'],['Outstanding',money(d.outstanding_balance),'Current']])}</div>`)}
async function email(){let [rows,status]=await Promise.all([api('/api/email'),api('/api/email/status')]);shell(`<div class="card"><div class="cardhead"><div><h2>Email</h2><p class="muted">Customer email notifications, payment reminders and operational messaging.</p></div><span class="badge ${status.configured?'good':''}">${status.configured?'CONNECTED':'NOT CONFIGURED'}</span></div><div class="toolbar"><button class="btn" onclick="emailForm()">+ Send Email</button><button class="btn secondary" onclick="queueEmailPaymentReminders()">Queue payment reminders</button><button class="btn secondary" onclick="queueEmailCollectionReminders()">Queue collection reminders</button><button class="btn secondary" onclick="dispatchEmail()">Dispatch queued</button></div><p class="muted">Configure SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD and SMTP_FROM on the server for live delivery.</p>${table(['To','Subject','Status','Attempts','Created'],rows.map(r=>`<tr><td>${esc(r.to_email)}</td><td>${esc(r.subject)}</td><td><span class="badge">${esc(r.status)}</span></td><td>${r.attempts}</td><td>${dt(r.created_at)}</td></tr>`).join(''))}</div>`)}
function emailForm(){modal('Send email',`<div class="form"><input id="eto" type="email" placeholder="Recipient email"><input id="esub" placeholder="Subject"><textarea id="emsg" placeholder="Message"></textarea></div><div class="actions"><button class="btn" onclick="sendEmail()">Send email</button></div>`)}
async function sendEmail(){await api('/api/email',{method:'POST',body:{to_email:eto.value,subject:esub.value,message:emsg.value}});modal.remove();email()}
async function queueEmailPaymentReminders(){let d=await api('/api/email/reminders/payments',{method:'POST'});alert(`${d.queued} payment reminders queued.`);email()}
async function queueEmailCollectionReminders(){let d=await api('/api/email/reminders/collection',{method:'POST'});alert(`${d.queued} collection reminders queued.`);email()}
async function dispatchEmail(){let d=await api('/api/email/dispatch',{method:'POST'});alert(`Sent: ${d.sent} | Failed: ${d.failed}`);email()}
async function whatsapp(){let [rows,status]=await Promise.all([api('/api/whatsapp/messages'),api('/api/whatsapp/status')]);shell(`<div class="card"><div class="cardhead"><div><h2>WhatsApp Business</h2><p class="muted">Customer self-service, notifications and support messaging.</p></div><span class="badge ${status.configured?'good':''}">${status.configured?'CONNECTED':'NOT CONFIGURED'}</span></div><div class="toolbar"><button class="btn" onclick="whatsappTextForm()">+ Send WhatsApp</button><button class="btn secondary" onclick="whatsappTemplateForm()">Send template</button></div><div class="notice"><b>Customer self-service:</b> customers can message your WhatsApp number and reply <b>MENU</b>, <b>1</b> for balance, <b>2</b> for collection status, <b>3</b> for payment information, or <b>4</b> for support.</div>${table(['Direction','Phone','Type','Message','Status','Time'],rows.map(r=>`<tr><td>${esc(r.direction)}</td><td>${esc(r.phone)}</td><td>${esc(r.message_type)}</td><td>${esc(r.message||r.template_name||'')}</td><td><span class="badge">${esc(r.status)}</span></td><td>${dt(r.created_at)}</td></tr>`).join(''))}</div>`)}
function whatsappTextForm(){modal('Send WhatsApp message',`<div class="form"><input id="wphone" placeholder="Ghana phone number"><textarea id="wtext" placeholder="Message"></textarea></div><div class="actions"><button class="btn" onclick="sendWhatsAppText()">Send</button></div>`)}
async function sendWhatsAppText(){await api('/api/whatsapp/send',{method:'POST',body:{phone:wphone.value,message:wtext.value}});modal.remove();whatsapp()}
function whatsappTemplateForm(){modal('Send approved WhatsApp template',`<div class="form"><input id="wtphone" placeholder="Ghana phone number"><input id="wtname" placeholder="Meta template name"><input id="wtlang" value="en_US" placeholder="Language code"><textarea id="wtcomponents" placeholder='Optional JSON components, e.g. []'></textarea></div><div class="actions"><button class="btn" onclick="sendWhatsAppTemplate()">Send template</button></div>`)}
async function sendWhatsAppTemplate(){let components=[];try{components=wtcomponents.value?JSON.parse(wtcomponents.value):[]}catch(e){return alert('Components must be valid JSON.')}await api('/api/whatsapp/template',{method:'POST',body:{phone:wtphone.value,template_name:wtname.value,language_code:wtlang.value||'en_US',components}});modal.remove();whatsapp()}
async function sms(){let rows=await api('/api/sms');shell(`<div class="card"><div class="toolbar"><button class="btn" onclick="smsForm()">+ Queue SMS</button><button class="btn secondary" onclick="queuePaymentReminders()">Queue payment reminders</button><button class="btn secondary" onclick="dispatchSMS()">Dispatch queued SMS</button></div><p class="muted">Set SMS_PROVIDER_URL, SMS_API_KEY and SMS_SENDER on the server to enable live delivery.</p>${table(['Phone','Message','Status','Attempts','Created'],rows.map(r=>`<tr><td>${esc(r.phone)}</td><td>${esc(r.message)}</td><td><span class="badge">${esc(r.status)}</span></td><td>${r.attempts}</td><td>${dt(r.created_at)}</td></tr>`).join(''))}</div>`)}
function smsForm(){modal('Queue customer SMS',`<div class="form"><input id="smsphone" placeholder="Ghana phone number"><textarea id="smstext" placeholder="Message"></textarea></div><div class="actions"><button class="btn" onclick="sendSMS()">Queue SMS</button></div>`)}
async function sendSMS(){await api('/api/sms',{method:'POST',body:{phone:smsphone.value,message:smstext.value}});modal.remove();sms()}
async function queuePaymentReminders(){let d=await api('/api/sms/reminders/payments',{method:'POST'});alert(`${d.queued} payment reminders queued.`);sms()}
async function dispatchSMS(){let d=await api('/api/sms/dispatch',{method:'POST'});alert(`Sent: ${d.sent} | Failed: ${d.failed}`);sms()}
async function audit(){let rows=await api('/api/audit');shell(`<div class="card"><div class="toolbar"><button class="btn secondary" onclick="exportData('audit')">Export audit CSV</button></div>${table(['Time','Actor','Action','Entity','Details'],rows.map(r=>`<tr><td>${dt(r.created_at)}</td><td>${esc(r.actor)}</td><td>${esc(r.action)}</td><td>${esc(r.entity)} #${esc(r.entity_id)}</td><td>${esc(r.details)}</td></tr>`).join(''))}</div>`)}
async function exportData(kind){const r=await fetch('/api/export/'+kind,{headers:{Authorization:'Bearer '+token}});if(!r.ok)return alert('Export failed');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='el_kalel_'+kind+'.csv';a.click();URL.revokeObjectURL(url)}
window.addEventListener('online',()=>{if(token&&page==='collections')syncOffline().catch(()=>{})});
if('serviceWorker' in navigator)navigator.serviceWorker.register('/static/sw.js').catch(()=>{});render();
